version: "3"
services:

  rb-3.0.0:
    image: digressed/test:edn_turbo-rb-3.0.0
    stdin_open: true
    tty: true

  rb-2.7.2:
    image: digressed/test:edn_turbo-rb-2.7.2
    stdin_open: true
    tty: true

  rb-2.6.6:
    image: digressed/test:edn_turbo-rb-2.6.6
    stdin_open: true
    tty: true

  rb-2.5.8:
    image: digressed/test:edn_turbo-rb-2.5.8
    stdin_open: true
    tty: true
